site_name: Peppol Project Documentation
site_url: https://peppoltest.github.io/test/
repo_url: https://github.com/PeppolTest/test
repo_name: GitHub

edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/PeppolWhite.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.expand
    - search.highlight
    - search.suggest
    - toc.integrate
    - navigation.instant
    - content.action.edit
    - content.action.view

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
      - MySQL setup: getting-started/mysql-setup.md
      - MySQL remote connection: getting-started/remote-connection.md
      - Database structure: getting-started/database-structure.md
  - Technical Documentation:
      - Overview: technical-documentation/index.md
      - invoice in: technical-documentation/invoice-in.md
      - invoice out: technical-documentation/invoice-out.md
      - peppol formatting: technical-documentation/peppol-formatting.md
  - FAQ: faq.md
  - Backup: backup.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
